### ISSUE TITLE
Add support to change BY_START_SEQUENCE

### ISSUE THREAD

**Issue by klayders** [nats-nui/nui#12]
When Consumer was created in jetstream, I need to change SEQUENCE position in my cosumer

**Comment by pricelessrabbit** [comment]
do you mean that you want to edit the start sequence of a consumer after the consumer creation? so for example:
- you have your consumer start on seq number 10
- you consume messages from 10 to 15
- you want to "reset" the consumer to redeliver messages from seq 10

In this case imho you have to re-create the consumer from scratch, because nats server has no support for a "consumer reset" (see  https://github.com/nats-io/nats-server/issues/4121). In fact, in [consumer config ](https://docs.nats.io/nats-concepts/jetstream/consumers#configuration) the `OptStartSeq` is not editable.

**Comment by klayders** [comment]
sorry, thanks
